version: '3.8'

services:
  # The FastAPI web server
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  # The Redis caching service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
